### ISSUE TITLE
正式仓什么时候发布？

### ISSUE THREAD

**Issue by ditokk** [snowballsecurities/snbpy#7]
- 正式仓什么时候发布
 - 查询支持时间区间查询吗？
 - 文档是否可以更完善些（示例）？
 
@chnyangjie 
 
🙏

**Comment by chnyangjie** [comment]
1. 现在 pypi 上已经有了1.0.2 版的 SDK. 可以直接使用 `pip install snbpy` 安装
1. [HTTP API DOC](https://snowballsecurities.github.io/api) 这里有详细的API 参数文档,和 SDK 是一样的.
    1. 其中历史成交有时间查询的功能.
    1. 订单查询只能查询当日订单(包括未成交 GTC), 没有历史订单的查询功能,所以没有时间范围的入参.
1. 文档迭代工作还在持续中,有任何的建议和订正欢迎提 PR.
